# Generated by Django 5.0.3 on 2024-03-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rssfeed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="etag",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="feed",
            name="modified",
            field=models.CharField(
                default="", max_length=200, verbose_name="last modified"
            ),
        ),
        migrations.AlterField(
            model_name="publication",
            name="id",
            field=models.CharField(
                max_length=200, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
