services:
  aptrade:
    image: aptrade
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      FLASK_DEBUG: 1
      FLASK_ENV: development
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"


  frontend:
    image: aptrade-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
