services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - FLASK_ENV=prodution
    image: aptrade-app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volume:
      - ./frontend:/frontend
    image: aptrade-frontend
    ports:
      - "3000:80"
