services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
      args:
        - FLASK_ENV=production
    image: aptrade-app
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: aptrade-frontend
    ports:
      - "3000:80"
