# Stage 1: Build
FROM node:18 AS build
WORKDIR /app

# Install dependencies
COPY ./frontend .
RUN npm install  && \
    npm run build


# Stage 2: Serve
FROM nginx:stable-alpine

# Copy custom Nginx configuration
COPY deployment/nginx.default.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

# Expose port and start Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
