version: "3.9"

x-env-common:
    &env-common
    env_file: 
    - path: ./default.env
      required: true
    - path: ./.env
      required: false
    networks:
        - djangonetwork

x-celery-common:
    &celery-common
    build: ./backend
    volumes:
    - ./backend:/usr/src/app
    << : *env-common
    environment:
        - DEBUG=${DJANGO_DEBUG}
        - SECRET_KEY=${SECRET_KEY}
        - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
        - CELERY_BROKER=${CELERY_BROKER}
        - CELERY_BACKEND=${CELERY_BACKEND}
        - POSTGRES_USER=${DJANGO_DB_USER}
        - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
        - POSTGRES_DB=${DJANGO_DB_NAME} 
    depends_on:
        - backend
        - redis


name: apttrade
services:
    backend:
        restart: always
        build: ./backend
        command: python manage.py runserver 0.0.0.0:8000
        image: django_backend
        << : *env-common
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/ur/src/app
        depends_on:
            - redis
            - db

    telegram:
        build: 
            context: ./telegram_bot
        << : *env-common
        volumes:
            - ./telegram_bot:/app
        ports:
            - 8080:8080

    db:
        image: postgres:16
        << : *env-common
        environment:
            - POSTGRES_USER=${DJANGO_DB_USER}
            - POSTGRES_PASSWORD=${DJANGO_DB_PASSWORD}
            - POSTGRES_DB=${DJANGO_DB_NAME} 
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"


    redis:
        image: "redis:alpine"
        ports: 
            - "6379:6379"
        networks:
            - djangonetwork



    celery:
        << : *celery-common
        command: celery --app=main worker --loglevel=info --logfile=logs/celery.log

    celery_flower:
        << : *celery-common
        command: celery -A main --broker=redis://redis:6379/0 flower  --port=5555 

    celery_beat:
        << : *celery-common
        command: celery --app=main beat -l info



#     ib-gateway:
#         restart: always
#         build:
#             context: ./services/ib-gateway-docker/stable
#             tags:
#                 - ib-gateway
#         image: ib-gateway
#         environment:
#             TWS_USERID: ${TWS_USERID}
#             TWS_PASSWORD: ${TWS_PASSWORD}
#             TRADING_MODE: ${TWS_TRADING_MODE:-paper}
#             TWS_SETTINGS_PATH: ${TWS_SETTINGS_PATH:-}
#             READ_ONLY_API: ${READ_ONLY_API:-}
#             VNC_SERVER_PASSWORD: ${VNC_SERVER_PASSWORD:-}
#             TWOFA_TIMEOUT_ACTION: ${TWOFA_TIMEOUT_ACTION:-exit}
#             BYPASS_WARNING: ${BYPASS_WARNING:-}
#             AUTO_RESTART_TIME: ${AUTO_RESTART_TIME:-}
#             AUTO_LOGOFF_TIME: ${AUTO_LOGOFF_TIME:-}
#             SAVE_TWS_SETTINGS: ${SAVE_TWS_SETTINGS:-}
#             RELOGIN_AFTER_TWOFA_TIMEOUT: ${RELOGIN_AFTER_TWOFA_TIMEOUT:-no}
#             TWOFA_EXIT_INTERVAL: ${TWOFA_EXIT_INTERVAL:-60}
#             TIME_ZONE: ${TIME_ZONE:-Etc/UTC}
#             TZ: ${TIME_ZONE:-Etc/UTC}
#             CUSTOM_CONFIG: ${CUSTOM_CONFIG:-NO}
#             SSH_TUNNEL: ${SSH_TUNNEL:-}
#             SSH_OPTIONS: ${SSH_OPTIONS:-}
#             SSH_ALIVE_INTERVAL: ${SSH_ALIVE_INTERVAL:-}
#             SSH_ALIVE_COUNT: ${SSH_ALIVE_COUNT:-}
#             SSH_PASSPHRASE: ${SSH_PASSPHRASE:-}
#             SSH_REMOTE_PORT: ${SSH_REMOTE_PORT:-}
#             SSH_USER_TUNNEL: ${SSH_USER_TUNNEL:-}
#             SSH_RESTART: ${SSH_RESTART:-}
#             SSH_VNC_PORT: ${SSH_VNC_PORT:-}
#         volumes:
#             - tws_tmp:/tmp # recommended for performance
#     #      - ${PWD}/jts.ini:/home/ibgateway/Jts/jts.ini
#     #      - ${PWD}/config.ini:/home/ibgateway/ibc/config.ini
#     #      - ${PWD}/tws_settings/:${TWS_SETTINGS_PATH:-/home/ibgateway/Jts}
#     #      - ${PWD}/ssh/:/home/ibgateway/.ssh
#         ports:
#             - "127.0.0.1:4001:4003"
#             - "127.0.0.1:4002:4004"
#             - "127.0.0.1:5900:5900"


# volumes:
#     tws_tmp:

networks:
    djangonetwork:
        driver: bridge
volumes:
  db_data:
