# Generated by Django 5.0.3 on 2024-03-16 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models



def populate_feed(apps, schema_editor):
    Feed = apps.get_model('rssfeed', 'Feed')
    data = {
        'name': 'FDA-1',
        'url': 'https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/drugs/rss.xml',
    }
    obj = Feed(**data)
    obj.save()

class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last update"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                (
                    "rssfeed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rssfeed.feed"
                    ),
                ),
            ],
            options={
                "db_table": "Publication",
            },
        ),
        migrations.RunPython(populate_feed),

    ]
