# Generated by Django 5.0.3 on 2024-03-16 20:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
import yaml
from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent
def populate_feed(apps, schema_editor):
    with open(os.path.join(BASE_DIR, 'fixtures', 'feed.yml'), 'r') as f:
        data = yaml.safe_load(f)
    Feed = apps.get_model('rssfeed', 'Feed')
    for entry in data:
        obj = Feed(**entry['fields'])
        obj.save()


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="last update"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date published"
                    ),
                ),
                (
                    "rssfeed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rssfeed.feed"
                    ),
                ),
            ],
            options={
                "db_table": "Publication",
            },
        ),
        migrations.RunPython(populate_feed),

    ]
