# Generated by Django 5.0.3 on 2024-03-15 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rssfeed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 3, 15, 21, 4, 22, 808988, tzinfo=datetime.timezone.utc
                        ),
                        verbose_name="date published",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Feed",
        ),
        migrations.AddField(
            model_name="rsssource",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 15, 21, 4, 22, 809305, tzinfo=datetime.timezone.utc
                ),
                verbose_name="last update",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="rssfeed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rssfeed.rsssource"
            ),
        ),
    ]
