# Generated by Django 5.0.3 on 2024-03-15 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rssfeed", "0002_publication_delete_feed_rsssource_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
        ),
        migrations.AlterField(
            model_name="rsssource",
            name="pub_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="last update"
            ),
        ),
    ]
